set_property SRC_FILE_INFO {cfile:/home/vladimir/TESTDIFFAC/cernv1/cernv1.srcs/constrs_1/imports/cern.git/ABB3_pcie_4_lane_EMu_FIFO_elink.xdc rfile:../../../cernv1.srcs/constrs_1/imports/cern.git/ABB3_pcie_4_lane_EMu_FIFO_elink.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X0Y2 [get_cells refclk_ibuf]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {make4Lanes.pcieCore/v7_pcie_i/pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S0}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {make4Lanes.pcieCore/v7_pcie_i/pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S1}]
